title: Research Virtual Machine Handbook

theme: minima


collections:
  docwindows:
    output: true
  doclinux:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
